/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export function BrownstoneText (props) {
    const { nodes, materials } = useGLTF("/PortfolioBrownstoneText.glb");
    
    const contact = useRef()

    useFrame(({clock}) => {
        const time = clock.getElapsedTime()
    //     contact.current.position.y = Math.cos(time)
    //     contact.current.position.x = Math.sin(time)
        
    })

    return (
    <group {...props} dispose={null}>
        <mesh
            ref={contact}
            castShadow
            receiveShadow
            geometry={nodes.Text.geometry}
            material={nodes.Text.material}
            position={[-11, 0.09, 0.02]}
            rotation={[0, -1.55, 0]}
            scale={1.58}
        >
            <meshBasicMaterial attach="material" color='mediumpurple' />
        </mesh>
    </group>
  );
}

useGLTF.preload("/PortfolioBrownstoneText.glb");
