/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export function Model(props) {
  const { nodes, materials } = useGLTF("/PortfolioBlock.glb");

  useFrame(({clock}) => {
    const a = clock.getElapsedTime()

    blade.current.rotation.y = a * 3
    
        // fanBlade.rotation.y = a * 3
        // girasol.rotation.x = a *2
  })

  const blade = useRef()
  return (
    <group {...props} dispose={null} >
      <mesh
        ref={blade}

        
        geometry={nodes.AC_Blade.geometry}
        material={materials["Material.013"]}
        position={[-0.83, 8.34, 7.51]}
        rotation={[0, -0.94, 0]}
        scale={[0.05, 0.06, 0.05]}
      />
      <group position={[-8.12, 10.98, 7.5]} scale={[0.89, 0.77, 1]}>
        <mesh

          
          geometry={nodes.Cube019.geometry}
          material={materials["Planter Paint"]}
        />
        <mesh

          
          geometry={nodes.Cube019_1.geometry}
          material={materials.Dirt}
        />
      </group>
      <group
        position={[-8.2, 10.99, -3.31]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.89, 0.77, 1]}
      >
        <mesh

          
          geometry={nodes.Cube020.geometry}
          material={materials["Planter Paint"]}
        />
        <mesh

          
          geometry={nodes.Cube020_1.geometry}
          material={materials.Dirt}
        />
      </group>
      <mesh

        
        geometry={nodes.Girasol_Stalk.geometry}
        material={materials.Girasol}
        position={[-7.71, 11.54, -2.84]}
        rotation={[0, -0.01, 0]}
        scale={[1, 0.27, 0.39]}
      />
      <mesh

        
        geometry={nodes.Light_Puck.geometry}
        material={nodes.Light_Puck.material}
        position={[-15.59, 15.02, -3.93]}
        scale={[0.25, 0.04, 0.25]}
      />
      <mesh

        
        geometry={nodes.Vertical_Lamp_Beam.geometry}
        material={materials["Material.011"]}
        position={[-10.62, 1.27, -8.38]}
      />
      <mesh

        
        geometry={nodes.Sidewalk.geometry}
        material={materials["Material.014"]}
      />
      <group position={[6.63, 0, 3.17]}>
        <mesh

          
          geometry={nodes.Cube002_1.geometry}
          material={materials["Material.004"]}
        />
        <mesh

          
          geometry={nodes.Cube002_2.geometry}
          material={materials["Material.008"]}
        />
        <mesh

          
          geometry={nodes.Cube002_3.geometry}
          material={materials["Material.009"]}
        />
        <mesh

          
          geometry={nodes.Cube002_4.geometry}
          material={materials["Material.010"]}
        />
      </group>
      <mesh

        
        geometry={nodes.Cube004.geometry}
        material={materials["Outer of AC"]}
        position={[-0.83, 7.4, 7.51]}
        scale={[1.28, 1, 1.28]}
      />
      <mesh

        
        geometry={nodes.Cube005.geometry}
        material={nodes.Cube005.material}
        position={[-4.51, 4.5, 10.99]}
      />
      <group position={[-4.51, 6.88, 10.99]}>
        <mesh

          
          geometry={nodes.About_Me_Sign_Border.geometry}
          material={materials["Sign Color"]}
        />
        <mesh

          
          geometry={nodes.About_Me_Sign_Border_1.geometry}
          material={materials["Material.003"]}
        />
        <mesh

          
          geometry={nodes.About_Me.geometry}
          material={nodes.About_Me.material}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.6, 0.29, 0.6]}
        />
      </group>
      <mesh

        
        geometry={nodes.Lamp_Head.geometry}
        material={materials["Material.012"]}
        position={[-15.59, 14.87, -3.93]}
      />
      <group
        position={[-7.71, 11.81, -2.84]}
        rotation={[Math.PI / 2, 0, -1.56]}
        scale={[-1, -0.04, -1]}
      >
        <mesh

          
          geometry={nodes.Cylinder006.geometry}
          material={materials["Material.017"]}
        />
        <mesh

          
          geometry={nodes.Cylinder006_1.geometry}
          material={materials["Girasol Red"]}
        />
        <mesh

          
          geometry={nodes.Cylinder006_2.geometry}
          material={materials["Blue Girasol"]}
        />
        <mesh

          
          geometry={nodes.Cylinder006_3.geometry}
          material={materials["Girasol Green"]}
        />
        <mesh

          
          geometry={nodes.Cylinder006_4.geometry}
          material={materials["Girasol Yellow"]}
        />
      </group>
      <mesh

        
        geometry={nodes.Horizontal_Lamp_Beam001.geometry}
        material={nodes.Horizontal_Lamp_Beam001.material}
        position={[-15.59, 10.58, -12.6]}
      />
      <mesh

        
        geometry={nodes.Cube001.geometry}
        material={materials["Outer of Main Building"]}
        position={[-3.06, 0, 3.17]}
        scale={[1, 2, 1]}
      />
      <mesh

        
        geometry={nodes.Horizontal_Lamp_Beam.geometry}
        material={nodes.Horizontal_Lamp_Beam.material}
        position={[-15.59, 14.91, -12.6]}
      />
      <mesh

        
        geometry={nodes.Cube003.geometry}
        material={materials["Material.006"]}
        position={[3.62, 0, -4.13]}
      />
    </group>
  );
}

useGLTF.preload("/PortfolioBlock.glb");
