/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function ProjectBuilding(props) {
    const { nodes, materials } = useGLTF("/projectBuilding.glb");
    return (
        <group {...props} dispose={null}>
        <group position={[6.5, 1.32, 0]}>
            <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube007.geometry}
            material={materials.ProjectBuildingMetal}
            />
            <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube007_1.geometry}
            material={materials.ProjectBuildingGlass}
            />
        </group>
        </group>
    );
}

useGLTF.preload("/projectBuilding.glb");

