/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

// import React, { useRef } from "react";
// import { useGLTF } from "@react-three/drei";

// export function Buzon(props) {
//     const { nodes, materials } = useGLTF("/Mailbox2.glb");
//     return (
//         <group {...props} dispose={null}>
//         <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Cube.geometry}
//             material={materials["Material.010"]}
//             position={[0.0, 0.2, 1]}
//             rotation={[0.4, -0.5, 0]}

//         />
//         </group>
//     );
// }

// useGLTF.preload("/Mailbox2.glb");

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Buzon(props) {
    const { nodes, materials } = useGLTF("/Mailbox3.glb");
    return (
        <group {...props} dispose={null}>
        <mesh
            geometry={nodes.Mailbox.geometry}
            material={materials["Material.010"]}
            position={[0.0, 0.2, 0]}
            rotation={[0.4, -0.5, 0]}
        />
        <mesh
            geometry={nodes.Plane.geometry}
            material={nodes.Plane.material}
            position={[-0.24, 1.45, 1.0]}
            rotation={[1.88, 0.1, Math.PI/6]}
            scale={[-0.33, -0.59, -0.44]}
        />
        </group>
    );
}

useGLTF.preload("/Mailbox3.glb");

