/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from "react";
import { useGLTF } from "@react-three/drei";
import { MeshPhysicalMaterial } from "three";
// import { MeshBasicMaterial } from "three";

export function Windows(props) {
  const { nodes, materials } = useGLTF("/BrownStoneWindows.glb");
  const [open, setOpen] = useState(false)

  const window = useRef()

  console.log(window)

    const handleClick = (e) => {
        setOpen(!open)
        console.log(open)
        
    }
  return (
    <group {...props} dispose={null}>
      <group>
      <mesh
        geometry={nodes["Window_Skinny_2-2002"].geometry}
        material={nodes["Window_Skinny_2-2002"].material}
        position={[-3.97816133, 1.81487918, -0.05916079]}
        scale={1.5}
      />
      <group
        position={[-2.98128057, -0.40516567, -0.05916079]}
        scale={1.5}
      >
        <mesh
          ref={window}
          castShadow
          geometry={nodes.Window_Skinny_1_Front001.geometry}
          // material={MeshPhysicalMaterial}
        >

        
          <meshPhysicalMaterial
                color="skyblue"
                transmission={1}
                thickness={0}
                roughness={0}
                envMapIntensity={1}
                clearcoat={1}
              />
        </mesh>
      </group>
      <mesh
        geometry={nodes.Windows_Wide_2_Eastside003.geometry}
        material={nodes.Windows_Wide_2_Eastside003.material}
        position={[-4.97504187, 1.79031968, -1.06895149]}
        scale={1.5}
      />
      <mesh
        geometry={nodes["Window_Skinny_2-3002"].geometry}
        material={nodes["Window_Skinny_2-3002"].material}
        position={[-4.97504187, 1.81487918, -0.05916079]}
        scale={1.5}
      />
      <mesh
        geometry={nodes.Window_Skinny_1_Back001.geometry}
        material={nodes.Window_Skinny_1_Back001.material}
        position={[-2.98128057, -0.42866445, -0.05916079]}
        scale={1.5}
      />
      <mesh
        geometry={nodes.Windows_Wide__1_Eastside001.geometry}
        material={nodes.Windows_Wide__1_Eastside001.material}
        position={[-4.97504187, 1.81958365, -1.06895149]}
        scale={1.5}
      />
      <mesh
        geometry={nodes["Window_Skinny_2-1003"].geometry}
        material={nodes["Window_Skinny_2-1003"].material}
        position={[-2.98128057, 1.79031968, -0.9086864]}
        scale={1.5}
      />
      <mesh
        geometry={nodes.Windows_WIde_2_Westside001.geometry}
        material={nodes.Windows_WIde_2_Westside001.material}
        position={[-4.97504187, 1.79031968, -1.06895149]}
        scale={1.5}
      />
      <mesh
        geometry={nodes.Windows_Wide__1_Westside001.geometry}
        material={nodes.Windows_Wide__1_Westside001.material}
        position={[3.77715731, 1.81560552, 0.29703289]}
        rotation={[-Math.PI, 1.5e-7, -Math.PI]}
        scale={1.5}
      />
      <mesh
        geometry={nodes["Window_Skinny_2-2003"].geometry}
        material={nodes["Window_Skinny_2-2003"].material}
        position={[-3.97816133, 1.79031968, -0.9086864]}
        scale={1.5}
      />
      <mesh
        geometry={nodes.Windows_Wide_2_Eastside004.geometry}
        material={nodes.Windows_Wide_2_Eastside004.material}
        position={[-4.9752264, 1.81246686, -1.06913412]}
        scale={[1.5, 1.50169897, 1.5]}
      />
      <mesh
        geometry={nodes["Window_Skinny_2-3003"].geometry}
        material={nodes["Window_Skinny_2-3003"].material}
        position={[-4.97504187, 1.79031968, -0.9086864]}
        scale={1.5}
      />
      <mesh
        geometry={nodes.Windows_Penhouse_Back.geometry}
        material={nodes.Windows_Penhouse_Back.material}
        position={[-2.98128057, 1.52641892, -1.48675871]}
        scale={1.5}
      />
      <mesh
        geometry={nodes.Windows_Wide_2_Eastside005.geometry}
        material={nodes.Windows_Wide_2_Eastside005.material}
        position={[-4.97504187, 1.79031968, -1.06895149]}
        scale={1.5}
      />
      <mesh
        geometry={nodes.Windows_Penthouse_Front001.geometry}
        material={nodes.Windows_Penthouse_Front001.material}
        position={[-2.98128057, 1.5, -1.48675871]}
        scale={1.5}
      />
      </group>
    </group>
    
  );
}

useGLTF.preload("/BrownStoneWindows.glb");

